AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Backup daily CloudFormation configuration
Resources:
    BackupPlan:
        Type: AWS::Backup::BackupPlan
        Properties:
            BackupPlan:
                BackupPlanName: THARUN
                BackupPlanRule:
                  - RuleName: "EC2-backups"
                    TargetBackupVault: !Ref 'BackupVault'
                    ScheduleExpression: cron(30 12 * * ?)
                    StartWindowMinutes: 60
                    Lifecycle:
                        DeleteAfterDays: 30

    BackupSelection:
        Type: AWS::Backup::BackupSelection
        Properties: 
            BackupPlanId: !Ref 'BackupPlan'
            BackupSelection: 
                SelectionName: tharun
                IamRoleArn: arn:aws:iam::983557702708:role/instance
                ListOfTags: 
                  - ConditionType: "STRINGEQUALS"
                    ConditionKey: "Name"
                    ConditionValue: "Production"
                             
    BackupVault:
        Type: AWS::Backup::BackupVault
        Properties: 
            BackupVaultName: "bACKUPvAULT"
        
        
