AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Backup daily CloudFormation configuration
Resources:
    BackupPlan:
        Type: AWS::Backup::BackupPlan
        Properties:
            BackupPlan:
                BackupPlanName: THARUN1
                BackupPlanRule:
                  - RuleName: "EC2-backups"
                    TargetBackupVault: !Ref 'BackupVault'
                    ScheduleExpression: cron(30 9 * * ?)
                    StartWindowMinutes: 60
                    Lifecycle:
                        DeleteAfterDays: 30

    BackupSelection:
        Type: AWS::Backup::BackupSelection
        Properties: 
            BackupPlanId: !Ref 'BackupPlan'
            BackupSelection: 
                SelectionName: tharun
                IamRoleArn: arn:aws:iam::983557702708:role/instance
                ListOfTags: 
                  - ConditionType: "STRINGEQUALS"
                    ConditionKey: "Environment"
                    ConditionValue: "Production"
                             
    BackupVault:
        Type: AWS::Backup::BackupVault
        Properties: 
            BackupVaultName: "bACKUPvAULT1"
            
Outputs:
  BackupSelectionName:
    Description: Tag:Value you need to put on your resource along with the Tag:Key Backup
    Value: !Ref BackupSelection
  BackupSelectionId:
    Description: Backup Selection ID
    Value: !Ref BackupSelection
  BackupVaultArn:
    Description: Backup Vault ARN
    Value: !GetAtt BackupVault.BackupVaultArn
  BackupPlanArn:
    Description: BackupPlan Arn
    Value: !GetAtt BackupPlan.BackupPlanArn
  BackupPlanId:
    Description: BackupPlan ID
    Value: !Ref BackupSelection
  BackupPlanVersionId:
    Description: BackupPlan Version ID
    Value: !GetAtt BackupPlan.VersionId            
        
        
